exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = qs
exec-once = hyprpaper
source = ~/.config/hypr/monitors-laptop.conf
$mainMod = SUPER

bind = $mainMod, RETURN, exec, foot
bind = SUPER, D, global, quickshell:launcher
bind = $mainMod, Q, killactive

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r

bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, J, movewindow, d
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, L, movewindow, r

binde = SUPER CTRL, H, resizeactive, -30 0
binde = SUPER CTRL, L, resizeactive, 30 0
binde = SUPER CTRL, K, resizeactive, 0 -30
binde = SUPER CTRL, J, resizeactive, 0 30

bind = SUPER, F, fullscreen, 0
bind = SUPER, A, togglefloating

bind = SUPER ALT, H, moveactive, -10 0
bind = SUPER ALT, L, moveactive, 10 0
bind = SUPER ALT, K, moveactive, 0 -10
bind = SUPER ALT, J, moveactive, 0 10

bind = SUPER, C, centerwindow
bind = SUPER, E, exec, foot -e yazi
bind = SUPER, W, exec, firefox
bind = SUPER CTRL, Q, exec, hyprlock

bind = SUPER, equal, global, quickshell:volume-up
bind = SUPER, minus, global, quickshell:volume-down
bind = SUPER, M, global, quickshell:volume-mute

bind = , PRINT, exec, ~/.local/bin/mire-screenshot full
bind = SUPER SHIFT, S, exec, ~/.local/bin/mire-screenshot area
bind = SUPER SHIFT, Q, exec, ~/.local/bin/mire-power
