general {
    hide_cursor = true
    grace = 0
	immediate_render = true
	no_fade_in = true
	no_fade_out = true
}

background {
    monitor =
    color = rgb(15111c)
}

label {
    monitor =
    text = Sungan
    color = rgb(b794f4)
    font_size = 34
    font_family = JetBrainsMono Nerd Font
    position = 0, 130
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(e8e4ee)
    font_size = 58
    font_family = JetBrainsMono Nerd Font
    position = 0, 35
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgb(8e8798)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -20
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 300, 48
    position = 0, -105

    halign = center
    valign = center

    outline_thickness = 1

    outer_color = rgb(9b6cff)
    inner_color = rgb(1d1826)
    font_color = rgb(e8e4ee)

    check_color = rgb(b794f4)
    fail_color = rgb(d35f5f)

    placeholder_text = <span foreground="##8e8798">Password...</span>

    dots_center = true
    fade_on_empty = false

    rounding = 12
}
