#!/usr/bin/env bash

set -e

DIR="$HOME/Pictures/Screenshots"
mkdir -p "$DIR"

file="$DIR/screenshot-$(date +'%Y-%m-%d_%H-%M-%S').png"

case "$1" in
    full)
        grim "$file"
        wl-copy < "$file"
        notify-send "Screenshot saved" "Copied to clipboard"
        ;;

    area)
        geometry="$(slurp)" || exit 0
        grim -g "$geometry" "$file"
        wl-copy < "$file"
        notify-send "Screenshot saved" "Copied to clipboard"
        ;;

    *)
        exit 1
        ;;
esac
