#!/usr/bin/env bash

set -e

CLASS="de.feschber.LanMouse"
WORKSPACE="lan-mouse"

if ! hyprctl clients -j | jq -e \
    --arg class "$CLASS" \
    '.[] | select(.class == $class)' \
    >/dev/null 2>&1
then
    hyprctl dispatch exec \
        "[workspace special:${WORKSPACE} silent] lan-mouse"

    sleep 0.7
fi

hyprctl dispatch togglespecialworkspace "$WORKSPACE"
